
*Ejercicios Tema 7: Sistemas de ecuaciones*
1. Crea una función en python que calcule la solución de un sistema de ecuaciones triangular inferior empleando el método de sustituciones progresivas. La función deberá tomar como valores de entrada una matriz triangular inferior de dimensión $(n\times n)$ arbitraria y un vector columna $(n\times 1)$ de términos independientes. Deberá devolver como variable de salida un vector columna $(n\times 1)$ con las soluciones del sistema.



In [65]:
import numpy as np
import sistemas as sis
import scipy as sc 

A=np.array([[2,0,0,0],[3,2,0,0],[2,5,7,0],[1,-2,3,4]])
b=np.ones([4,1])
x=sis.progressive(A, b)
print(x)
print(np.dot(A,x))

[[ 0.5       ]
 [-0.25      ]
 [ 0.17857143]
 [-0.13392857]]
[[1.]
 [1.]
 [1.]
 [1.]]



2. Crea una función en python que calcule la solución de un sistema de ecuaciones triangular superior empleando el método de sustituciones regresivas. La función deberá tomar como valores de entrada una matriz triangular inferior de dimensión $(n\times n)$ arbitraria y un vector columna $(n\times 1)$ de términos independientes. Deberá devolver un vector columna $(n\times 1)$ con las soluciones del sistema.
`

In [66]:
A=np.array([[1.,-3.,-6.,4.],[0.,2.,3.,-1.],[0.,0.,-5.,1.],[0.,0.,0.,3.]])
b=np.ones([4,1])
x=sis.regressive(A,b)
print(x)
print(np.dot(A,x))

[[ 1.46666667]
 [ 0.86666667]
 [-0.13333333]
 [ 0.33333333]]
[[1.]
 [1.]
 [1.]
 [1.]]



3. Crea una función que dadas una matriz cuadrada  $ A,\ (n\times n)$ y un  vector columna $b,\ (n\times 1)$, construya la matriz ampliada $Ab$, Aplique el método de eliminación gausiana a la matriz ampliada y llame a la función creada en el ejercicio \ref{eje62} Para resolver el sistema $Ax=b$. La función deberá devolver como variables de salida, La matriz resultante de la aplicar la eliminación gaussiana a la ampliada y un vector columna con las soluciones del sistema resuelto. 



In [67]:
A=np.array([[1.,3.,2.],[2.,-1.,1.],[1.,4.,3.]])
b=np.array([[13.],[3.],[18.]])
U,x=sis.gaussSolve(A,b)
print("U: ",U)
print("x: ",x)

[[ 2. -1.  1.  3.]
 [ 1.  3.  2. 13.]
 [ 1.  4.  3. 18.]]
[[ 2.  -1.   1.   3. ]
 [ 0.   4.5  2.5 16.5]
 [ 0.   3.5  1.5 11.5]]
[[ 2.         -1.          1.          3.        ]
 [ 0.          4.5         2.5        16.5       ]
 [ 0.          0.         -0.44444444 -1.33333333]]
U:  [[ 2.         -1.          1.          3.        ]
 [ 0.          4.5         2.5        16.5       ]
 [ 0.          0.         -0.44444444 -1.33333333]]
x:  [1. 2. 3.]


In [68]:
U=sis.gaussJordanC(A,b)
print(U)

[[ 1.00000000e+00  0.00000000e+00 -4.93432455e-17  1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -9.86864911e-17  2.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00  3.00000000e+00]]


5. Construye un programa que resuelva un sistema de ecuaciones de dimensión arbitraria, empleando el método de Jacobi simple (no en forma matricial). El programa deberá admitir como variables de entrada, una matriz de coeficientes $ A,\ (n\times n)$, un vector de términos independientes $b,\ (n\times 1)$, una solución inicial $x_0 ,\ (n\times 1)$, un valor para la tolerancia máxima entre dos iteraciones sucesivas y un número máximo de iteraciones permitido. El programa deberá devolver un vector columna con las soluciones del sistema, el número de iteraciones empleado y el error relativo entre las dos últimas iteraciones realizadas.


In [69]:
A=np.array([[4., 2.,-1.],[3., -5., 1.],[1., -1., 6.]])
b=np.array([[5.],[-4.],[17.]])
x0=np.zeros([3,1])
tol=0.00001
itmax=50
x,error,it=sis.jacobiIt(A, b, x0, tol, itmax)
print("x:",x,"\n error: ",error, "\n it= ",it)
print("b: ",b)
print(A.dot(x))

x: [[0.99999796]
 [1.9999964 ]
 [3.0000017 ]] 
 error:  8.847091789874065e-06 
 it=  23
b:  [[ 5.]
 [-4.]
 [17.]]
[[ 4.99998297]
 [-3.99998643]
 [17.00001173]]


6. Repite el ejercicio anterior empleando ahora el método de Jacobi matricial. Añade el código necesario para que calcule en primer lugar el radio espectral de la matriz del método y caso de no cumplirse  la condición de convergencia, el programa interrumpa su ejecución y devuelva un mensaje de error indicando el valor del radio espectral.


In [70]:
A=np.array([[4., 2.,-1.],[3., -5., 1.],[1., -1., 6.]])
b=np.array([[5.],[-4.],[17.]])
x0=np.zeros([3,1])
tol=0.00001
itmax=50
x,error,it=sis.jacobi(A, b, x0, tol, itmax)
print("x:",x,"\n error: ",error, "\n it= ",it)
A=np.array([[1,2,-1],[2,-5,1],[1,-1,3]])
x,error,it=sis.jacobi(A, b, x0, tol, itmax)
print("x:",x,"\n error: ",error, "\n it= ",it)


x: [[0.99999796]
 [1.9999964 ]
 [3.0000017 ]] 
 error:  8.84709178996776e-06 
 it=  23
The system does not converge. Spectral radius greater than 1:  1.0597398959658624
x: [[0.]
 [0.]
 [0.]] 
 error:  18.16590212458495 
 it=  0


7. Construye un programa que resuelva un sistema de ecuaciones de dimensión arbitraria, empleando el método de Gauss-Seidel simple (no en forma matricial). El programa deberá admitir como variables de entrada, una matriz de coeficientes $ A,\ (n\times n)$, un vector de términos independientes $b,\ (n\times 1)$, una solución inicial $x_0 ,\ (n\times 1)$, un valor para la tolerancia máxima entre dos iteraciones sucesivas y un número máximo de iteraciones permitido. El programa deberá devolver un vector columna con las soluciones del sistema, el número de iteraciones empleado y el error relativo entre las dos últimas iteraciones realizadas.


In [71]:
A=np.array([[4., 2.,-1.],[3., -5., 1.],[1., -1., 6.]])
b=np.array([[5.],[-4.],[17.]])
x0=np.zeros([3,1])
tol=0.00001
itmax=50
x,error,it=sis.gaussSeidelIt(A, b, x0, tol, itmax)
print("x:",x,"\n error: ",error, "\n it= ",it)
print(A.dot(x))

x: [[0.9999991 ]
 [1.99999943]
 [3.00000005]] 
 error:  4.2723667257972726e-06 
 it=  13
[[ 4.9999952 ]
 [-3.99999978]
 [17.        ]]



8. Repite el ejercicio anterior empleando ahora el método de Gauss-Seidel matricial. Añade el código necesario para que calcule en primer lugar el radio espectral de la matriz del método y caso de no cumplirse  la condición de convergencia, el programa interrumpa su ejecución y devuelva un mensaje de error indicando el valor del radio espectral.


In [72]:
x,error,it=sis.gaussSeidel(A, b, x0, tol, itmax)
print("Gauss Seidel")
print("x:",x,"\n error: ",error, "\n it= ",it)

Gauss Seidel
x: [[0.9999991 ]
 [1.99999943]
 [3.00000005]] 
 error:  4.27236672600987e-06 
 it=  13


9. Construye un programa que resuelva un sistema de ecuaciones de dimensión arbitraria, empleando el método de Jacobi amortiguado simple (no en forma matricial). El programa deberá admitir como variables de entrada, una matriz de coeficientes $ A,\ (n\times n)$, un vector de términos independientes $b,\ (n\times 1)$, una solución inicial $x_0 ,\ (n\times 1)$, un valor para el parámetro de amortiguamiento $\omega$, un valor para la tolerancia máxima entre dos iteraciones sucesivas y un número máximo de iteraciones permitido. El programa deberá devolver un vector columna con las soluciones del sistema, el número de iteraciones empleado y el error relativo entre las dos últimas iteraciones realizadas.


In [73]:
print("Jacobi amortiguado")
x,error,it=sis.jacobiItW(A, b, x0, tol, itmax, 0.8)
print("x:",x,"\n error: ",error, "\n it= ",it)

Jacobi amortiguado
x: [[1.00000231]
 [2.0000016 ]
 [2.9999989 ]] 
 error:  5.681694716002063e-06 
 it=  18


10. Repite el ejercicio anterior empleando ahora el método de Jacobi amortiguado matricial. Añade el código necesario para que calcule en primer lugar el radio espectral de la matriz del método y caso de no cumplirse  la condición de convergencia, el programa interrumpa su ejecución y devuelva un mensaje de error indicando el valor del radio espectral.


In [74]:
print("Jacobi amortiguado matricial")
x,error,it=sis.jacobiW(A, b, x0, tol, itmax, 0.8)
print("x:",x,"\n error: ",error, "\n it= ",it) 
A=np.array([[1,2,-1],[2,-5,1],[1,-1,3]])
x,error,it=sis.jacobiW(A, b, x0, tol, itmax, 1)
print("x:",x,"\n error: ",error, "\n it= ",it) 


Jacobi amortiguado matricial
x: [[1.00000231]
 [2.0000016 ]
 [2.9999989 ]] 
 error:  5.681694716391025e-06 
 it=  18
The system does not converge. Spectral radius greater than 1:  1.0597398959658624
x: [[0.]
 [0.]
 [0.]] 
 error:  18.16590212458495 
 it=  0


11. Construye un programa que resuelva un sistema de ecuaciones de dimensión arbitraria, empleando el método SOR  simple (no en forma matricial). El programa deberá admitir como variables de entrada, una matriz de coeficientes $ A,\ (n\times n)$, un vector de términos independientes $b,\ (n\times 1)$, una solución inicial $x_0 ,\ (n\times 1)$, un valor para el parámetro de amortiguamiento $\omega$, un valor para la tolerancia máxima entre dos iteraciones sucesivas y un número máximo de iteraciones permitido. El programa deberá devolver un vector columna con las soluciones del sistema, el número de iteraciones empleado y el error relativo entre las dos últimas iteraciones realizadas.


In [75]:
A=np.array([[4., 2.,-1.],[3., -5., 1.],[1., -1., 6.]])
b=np.array([[5.],[-4.],[17.]])
x0=np.zeros([3,1])
tol=0.00001
itmax=50
w=0.8
x,error,it=sis.gaussSeideSORlIt(A, b, x0, tol, itmax, w)
print("x:",x,"\n error: ",error, "\n it= ",it)

x: [[1.00000187]
 [1.99999956]
 [2.99999956]] 
 error:  5.96580329442439e-06 
 it=  11


12. Repite el ejercicio anterior empleando ahora el método SOR matricial. Añade el código necesario para que calcule en primer lugar el radio espectral de la matriz del método y caso de no cumplirse  la condición de convergencia, el programa interrumpa su ejecución y devuelva un mensaje de error indicando el valor del radio espectral.


In [76]:
print("SOR matricial")
A=np.array([[4., 2.,-1.],[3., -5., 1.],[1., -1., 6.]])
b=np.array([[5.],[-4.],[17.]])
x0=np.zeros([3,1])
tol=0.00001
itmax=50
w=0.8
x,error,it=sis.SOR(A, b, x0, tol, itmax, w)
print("x:",x,"\n error: ",error, "\n it= ",it)
A=np.array([[1,2,-1],[2,-5,1],[1,-1,3]])
w=1
x,error,it=sis.SOR(A, b, x0, tol, itmax, w)
print("x:",x,"\n error: ",error, "\n it= ",it)

SOR matricial
x: [[1.00000187]
 [1.99999956]
 [2.99999956]] 
 error:  5.965803294477046e-06 
 it=  11
The system does not converge. Spectral radius greater than 1:  1.0592129611543726
x: [[0.]
 [0.]
 [0.]] 
 error:  18.16590212458495 
 it=  0



12. Resuelve el siguiente sistema de ecuaciones, empleando la factorización LU. Indica todos los pasos empleados hasta obtener las solución del sistema.

$$ 3x_1+3x_2-2x_3 +x_4= 13 $$

$$2 x_2-x_3  \hspace{30pt} =3$$

$$ -2x_1+x_2 + 5x_3 -4x_4= 1$$

$$ 2x_1 \hspace{30pt} - x_3 +2x_4 = 5 $$

Repite el ejercicio empleando las factorizaciones QR y SVD.


In [77]:
A=np.array([[3.,3.,-2.,1],[0.,2.,-1.,0.],[-2.,1.,5.,-4.],[2.,0.,-1.,2.]])
b=np.array([[13.],[3.],[1.],[5.]])
P,L,U=sc.linalg.lu(A)
print("L:",L)
print("U:",U)
print("P: ",P)
Pb=np.transpose(P).dot(b)
print("Pb: ",Pb)
z=sis.progressive(L, Pb)
print("z:",z)
print("Lz: ",L.dot(z))
x=sis.regressive(U, z)
print("x:",x)
print(A.dot(x))
#QR factorising
c
#SVD decomposition
U,s,V=sc.linalg.svd(A)
print("U: ",U)
print("V: ",V)
print("s: ",s)
S=np.diag(s)
print("S: ",S)
Utb=np.transpose(U).dot(b)
z=sis.diag_sys(S, Utb)
print("z: ",z)
x=np.transpose(V).dot(z)
print("x:",x)


L: [[ 1.          0.          0.          0.        ]
 [-0.66666667  1.          0.          0.        ]
 [ 0.          0.66666667  1.          0.        ]
 [ 0.66666667 -0.66666667 -0.80645161  1.        ]]
U: [[ 3.          3.         -2.          1.        ]
 [ 0.          3.          3.66666667 -3.33333333]
 [ 0.          0.         -3.44444444  2.22222222]
 [ 0.          0.          0.          0.90322581]]
P:  [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
Pb:  [[13.]
 [ 1.]
 [ 3.]
 [ 5.]]
z: [[ 1.30000000e+01]
 [ 9.66666667e+00]
 [-3.44444444e+00]
 [ 4.44089210e-16]]
Lz:  [[13.]
 [ 1.]
 [ 3.]
 [ 5.]]
x: [[3.00000000e+00]
 [2.00000000e+00]
 [1.00000000e+00]
 [4.91670197e-16]]
[[13.]
 [ 3.]
 [ 1.]
 [ 5.]]


NameError: name 'c' is not defined


13. Para calcular las intensidades de un circuito de corriente continua como el de la figura, es suficiente emplear las leyes de Kirchoff. La primera ley **ley de nodos** establece que la suma de corrientes que llegan a un nodo del circuito debe ser igual a cero.

La segunda **ley de mallas** establece que la suma de las caídas de tensión en un malla cerrada tiene que ser cero. La caída de voltaje en una resistencia se calcula empleando la ley de Ohm: $V = i\cdot R$
Si aplicamos las leyes de Kirchoff al circuito de la figura, obtenemos  el siguiente sistema de ecuaciones,

\begin{align*}
i_1 - i_2 - i_3 &= 0\\
i_3 - i_4 - i_5 &= 0\\
i_5  + i_2 -i_6&= 0\\
5i_3 + 70 i_4 &= 180\\
25i_2 -5i_3-10i_5 &= 0\\
10i_5+8i_6 -70i_4 &= 0  
\end{align*}

<image src="/images/circuito.eps">

Las tres primeras ecuaciones corresponden a aplicar la **ley de nodos** a los nodos marcados con un punto negro en la figura. 

Las tres últimas, a aplicar la **ley de mallas** a las tres mallas considerando positivo recorrerlas en el sentido de las agujas del reloj.

El sistema de ecuaciones obtenido puede expresarse en forma matricial como,
\begin{equation}
\begin{pmatrix}
1& -1& -1& 0 & 0 &0\\
0& 0& 1& -1& -1& 0\\
0& 1& 0&  0&  1& -1\\ 
0& 0& 5& 70& 0& 0\\
0& 25& -5& 0& -10& 0\\
0& 0& 0& -70& 10& 8
\end{pmatrix}\begin{pmatrix}
i_1\\ i_2\\ i_3\\ i_4\\ i_5\\ i_6
\end{pmatrix}= \begin{pmatrix}
0\\ 0\\ 0\\ 180\\ 0\\ 0
\end{pmatrix} 
\end{equation}
    
1. Define en python el sistema de ecuaciones anterior. Obtén los valores de las intensidades en todas las ramas del circuito empleando directamente un solo comando o función de python. Calcula el condicionamiento del sustema y dí si en tu opinión el sistema está bien o mal condicionado.


In [81]:
A=np.array([[1.,-1.,-1.,0.,0.,0.],[0.,0.,1.,-1,-1.,0.],[0.,1.,0.,0.,1.,-1.],[0.,0.,5.,70.,0.,0.],[0.,25.,-5.,0.,-10.,0.],[0.,0.,0.,-70.,10.,8.]])
b=np.array([[0.],[0.],[0.],[180.],[0.],[0.]])
condicionamiento=np.linalg.cond(A)
print("Condicionamiento: ",condicionamiento)
x=(np.linalg.inv(A)).dot(b)
print("x: ", x)

Condicionamiento:  148.87162008127189
x:  [[12.]
 [ 4.]
 [ 8.]
 [ 2.]
 [ 6.]
 [10.]]



2. Emplea la factorización QR para obtener de nuevo la solución del sistema. 


In [82]:
Q,R=sc.linalg.qr(A)
print("Q: ",Q)
print("R: ", R)
Qb=np.transpose(Q).dot(b)
x=sis.regressive(R, Qb)
print("x: ",x)

Q:  [[ 1.          0.          0.          0.          0.          0.        ]
 [-0.          0.         -0.19596569  0.20121156  0.91167056 -0.29994691]
 [-0.         -0.03996804 -0.03913053  0.03738837 -0.3268157  -0.94269028]
 [-0.         -0.         -0.97982845 -0.04173785 -0.16926148  0.09769699]
 [-0.         -0.99920096  0.00156522 -0.00149553  0.01307263  0.03770761]
 [-0.         -0.         -0.          0.9779426  -0.18228535  0.10198195]]
R:  [[ 1.00000000e+00 -1.00000000e+00 -1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.50199920e+01  4.99600479e+00  0.00000000e+00
   9.95204155e+00  3.99680383e-02]
 [ 0.00000000e+00  0.00000000e+00 -5.10293407e+00 -6.83920261e+01
   1.41182950e-01  3.91305293e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.15788430e+01
   9.63055818e+00  7.78615245e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.19206603e+00 -1.13146710e+00]
 [ 0.00000000e+00  0.00000000e+00  0

3. Utilizando la versión permutada del sistema, obtenida mediante la factorización LU, es decir, usando $P\cdot A$ como matriz del sistema y $P\cdot b$, como término independiente, calcula el radio espectral correspondiente al método de Jacobi e indica si tiene sentido o no emplear este método para obtener las intensidades del circuito de la figura.


In [84]:
P,L,U=sc.linalg.lu(A)
pA=np.transpose(P).dot(A)
pb=np.transpose(P).dot(b)
print("pA: ",pA)
x0=np.zeros([6,1])
tol=0.00001
itmax=50
x=sis.jacobi(pA,pb,x0,tol,itmax)

pA:  [[  1.  -1.  -1.   0.   0.   0.]
 [  0.  25.  -5.   0. -10.   0.]
 [  0.   0.   5.  70.   0.   0.]
 [  0.   0.   0. -70.  10.   8.]
 [  0.   0.   1.  -1.  -1.   0.]
 [  0.   1.   0.   0.   1.  -1.]]
The system does not converge. Spectral radius greater than 1:  1.4728937596850245


4. Emplea el método de Jacobi amortiguado, con un amortiguamiento de $w =0.1$ para calcular las intensidades del circuito de la figura, con una tolerancia de $10^{-5}$. Indica el número de iteraciones empleado hasta alcanzar la solución.  (**Nota importante**} Usa la versión permutada del sistema y ten en cuenta que va a necesitar bastantes iteraciones --más de $3000$-- para converger).


In [85]:
w=0.1
tol=0.00001
itmax=4000
x, error, it = sis.jacobiW(pA,pb,x0,tol,itmax,w)
print("x:",x,"\n error: ",error, "\n it= ",it)

x: [[11.99995837]
 [ 3.99998705]
 [ 7.99992688]
 [ 2.00000195]
 [ 5.99994733]
 [ 9.99999716]] 
 error:  9.750404786690157e-06 
 it=  3078


5. Emplea el método SOR, con un amortiguamiento de $w =0.2$ para calcular las intensidades del circuito de la figura, con una tolerancia de $10^{-5}$. Indica el número de iteraciones empleado hasta alcanzar la solución (**Nota importante:** Usa la versión permutada del sistema).

Discute, a la vista de los resultados, cúal método funciona mejor.


In [86]:
w=0.2
tol=0.00001
itmax=4000
x, error, it = sis.SOR(pA,pb,x0,tol,itmax,w)
print("x:",x,"\n error: ",error, "\n it= ",it)

x: [[11.99999295]
 [ 3.99999735]
 [ 8.00001175]
 [ 1.9999987 ]
 [ 6.00001305]
 [10.00001041]] 
 error:  8.613785306012668e-06 
 it=  116


6. Escribe un código que permita dibujar el radio espectral de un método amortiguado en función de la matriz del método, para distintos valores del amortiguamiento. Emplea el programa para los casos de las dos preguntas anteriores. ¿Ha sido razonable la elección de los valores de $w$ realizada en dichas preguntas?

In [92]:
sis.spectralRadPlot(pA,0)
sis.spectralRadPlot(pA,1)
